services:
  postgres:
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: job_applications_dev
    volumes:
      - job_offers_data:/var/lib/postgresql/data

volumes:
  job_offers_data: