services:
  postgres:
    container_name: postgres
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: job_applications
    volumes:
      - job_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  job-applications:
      image: ghcr.io/ztec22/job-applications:latest
      ports:
        - "4000:4000"
      environment:
        DATABASE_URL: "postgres://postgres:postgres@postgres/job_applications"
        SECRET_KEY_BASE: __super_secret_super_secret_super_secret_super_secret_super_secret__
      depends_on:
        postgres:
          condition: service_healthy
          restart: true
volumes:
  job_data:
